# -*- coding: utf-8 -*-
"""internshipweek1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiVBKC110ccBr_HAjLM9UmFdeAJY1EH-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""TASK 1 DATA COLLECTION & UNDERSTANDING"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df.head()

df.head()
df.shape

df.columns

df.dtypes

df.info()

df.describe()

df.isnull().sum()

"""The Netflix Titles dataset contains information about movies and TV shows available on Netflix. It includes details such as title, director, cast, country, release year, rating, duration, genre, and description. The dataset is useful for performing data analysis, visualization, and trend identification in entertainment content.

TASK 2 DATA CLEANING & PREPROCESSING
"""

df.fillna("Unknown", inplace=True)

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df.info()

df.head()

"""Missing values were identified and handled using placeholder values. Duplicate records were removed to improve data quality. The date_added column was converted into datetime format for better analysis and visualization.

TASK 3 EXPLORATORY DATA ANALYSIS
"""

df['type'].value_counts()

df['country'].value_counts().head(10)

df['rating'].value_counts().head(10)

"""TASK 4 DATA VISUALIZATION"""

sns.countplot(x='type', data=df)

plt.title("Movies vs TV Shows on Netflix")

plt.show()

top_countries = df['country'].value_counts().head(10)

top_countries.plot(kind='bar')

plt.title("Top 10 Countries with Most Netflix Content")

plt.show()

sns.countplot(y='rating',
data=df,
order=df['rating'].value_counts().index[:10])

plt.title("Most Common Ratings")

plt.show()

numeric_df = df.select_dtypes(include=['number'])

sns.heatmap(numeric_df.corr(), annot=True)

plt.title("Correlation Heatmap")

plt.show()

"""TASK 5 PREDICTIVE MODEL"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

ml_df = df[['type', 'release_year']]

ml_df = df[['type', 'release_year']].copy()

encoder = LabelEncoder()

ml_df['type'] = encoder.fit_transform(ml_df['type'])

X = ml_df[['release_year']]
y = ml_df['type']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

model = LogisticRegression()

model.fit(X_train, y_train)

print(model.score(X_test, y_test))